W5D1/GoalSetter/config/routes.rb
Rails.application.routes.draw do
  resources :goal_comments
  resources :user_comments
  resources :goals
  resources :users, only: [:new, :create]
  resource :session, only: [:new, :create, :destroy]
end

W5D1/GoalSetter/app/models/goal.rb
# == Schema Information
#
# Table name: goals
#
#  id         :integer          not null, primary key
#  title      :string
#  body       :text
#  user_id    :integer
#  private    :boolean
#  complete   :boolean
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Goal < ActiveRecord::Base
  validates :title, :body, :user, presence: true
  validates :private, :complete, default: false

  belongs_to :user
end

W5D1/GoalSetter/app/models/goal_comment.rb
# == Schema Information
#
# Table name: goal_comments
#
#  id         :integer          not null, primary key
#  author_id  :integer          not null
#  goal_id    :integer          not null
#  body       :text             not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class GoalComment < ActiveRecord::Base
  validates :author, :goal, :body, presence: true

  belongs_to :author, class_name: "User"

  belongs_to :goal
end

W5D1/GoalSetter/app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  username        :string           not null
#  password_digest :string           not null
#  session_token   :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ActiveRecord::Base
  validates :username, :password_digest, :session_token, presence: true
  validates :password, length: { minimum: 6, allow_nil: true }
  after_initialize :ensure_session_token

  has_many :goals

  attr_reader :password

  def password=(new_password)
    @password = new_password
    self.password_digest = BCrypt::Password.create(new_password)
  end

  def self.find_by_credentials(username, password)
    user = User.find_by(username: username)
    user && user.is_password?(password) ? user : nil
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def reset_session_token!
    generate_session_token
    self.save!
    self.session_token
  end

  def generate_session_token
    self.session_token = SecureRandom.urlsafe_base64
  end

  def ensure_session_token
    self.session_token ||= generate_session_token
  end

end

W5D1/GoalSetter/app/models/user_comment.rb
# == Schema Information
#
# Table name: user_comments
#
#  id         :integer          not null, primary key
#  author_id  :integer          not null
#  user_id    :integer          not null
#  body       :text             not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class UserComment < ActiveRecord::Base
  validates :author, :user, :body, presence: true

  belongs_to :author, class_name: "User"

  belongs_to :user
end

W5D1/GoalSetter/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user, :logged_in?

  def current_user
    User.find_by(session_token: session[:session_token])
  end

  def logged_in?
    !!current_user
  end

  def log_in!(user)
    session[:session_token] = user.session_token
  end

  def require_logged_in
    redirect_to new_session_url unless logged_in?
  end
end

W5D1/GoalSetter/app/controllers/goal_comments_controller.rb
class GoalCommentsController < ApplicationController
end

W5D1/GoalSetter/app/controllers/goals_controller.rb
class GoalsController < ApplicationController
  before_action :require_logged_in

  def new

    render :new
  end

  def create
    new_goal = Goal.new(goal_params)
    new_goal.user = current_user
    if new_goal.save
      redirect_to goal_url(new_goal)
    else
      flash.now[:errors] = new_goal.errors.full_messages
      render :new
    end
  end

  def edit
    @goal = Goal.find(params[:id])
    render :edit
  end

  def update
    goal = Goal.find(params[:id])

    if goal && goal.user == current_user
      if goal.update(goal_params)
        redirect_to goal_url(goal)
      else
        flash.now[:errors] = goal.errors.full_messages
        render :edit
      end
    else
      flash[:errors] = ["Not permitted to edit."]
      redirect_to goals_url
    end
  end

  def show
    @goal = Goal.find(params[:id])
    if @goal
      if @goal.private && current_user != @goal.user
        flash[:errors] = ["Private!!"]
        redirect_to goals_url
      else
        render :show
      end
    else
      flash[:errors] = ["Invalid goal"]
      redirect_to goals_url
    end
  end

  def destroy
    goal = Goal.find(params[:id])
    if goal.destroy
      redirect_to goals_url
    else
      flash[:errors] = goals.errors.full_messages
      redirect_to goals_url
    end
  end

  def index
    @goals = current_user.goals
    render :index
  end

  private
  def goal_params
    params.require(:goal).permit([:title, :body, :complete, :private])
  end
end

W5D1/GoalSetter/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    user = User.find_by_credentials(params[:user][:username], params[:user][:password])
    if user
      log_in!(user)
      redirect_to goals_url
    else
      flash.now[:errors] = ["Invalid username/password."]
      render :new
    end
  end

  def destroy
    current_user.try(:reset_session_token!)
    session[:session_token] = nil
    render :new
  end

end

W5D1/GoalSetter/app/controllers/user_comments_controller.rb
class UserCommentsController < ApplicationController
end

W5D1/GoalSetter/app/controllers/users_controller.rb
class UsersController < ApplicationController

  def create
    new_user = User.new(user_params)
    if new_user.save
      log_in!(new_user)
      redirect_to goals_url
    else
      flash.now[:errors] = new_user.errors.full_messages
      render :new
    end

  end

  private
  def user_params
    params.require(:user).permit(:username, :password)
  end
end

W5D1/GoalSetter/app/helpers/application_helper.rb
module ApplicationHelper
  def auth_token
    "<input type='hidden'
      name='authenticity_token'
      value='#{ form_authenticity_token }'>".html_safe
  end
end

W5D1/GoalSetter/app/helpers/goal_comments_helper.rb
module GoalCommentsHelper
end

W5D1/GoalSetter/app/helpers/goals_helper.rb
module GoalsHelper
end

W5D1/GoalSetter/app/helpers/user_comments_helper.rb
module UserCommentsHelper
end

W5D1/GoalSetter/app/helpers/users_helper.rb
module UsersHelper
end

W5D1/GoalSetter/app/views/goals/edit.html.erb
<h2>Edit goal</h2>
<form class="" action="<%= goal_url(@goal) %>" method="post">
  <%= auth_token %>
  <input type="hidden" name="_method" value="PATCH">

  <label for="title">Title</label>
  <input type="text" name="goal[title]" value="<%= @goal.title %>" id="title">

  <br>
  <label for="body">Body</label>
  <input type="text" name="goal[body]" value="<%= @goal.body %>" id="body">
  <br>
  <input type="submit" value="submit">
</form>

W5D1/GoalSetter/app/views/goals/index.html.erb
<h2>All goals</h2>
<ul>

<% @goals.each do |goal| %>
  <li><a href="<%= goal_url(goal) %>"><%= goal.title %></a></li>
<% end %>

</ul>
<a href="<%= new_goal_url %>">new goal</a>

W5D1/GoalSetter/app/views/goals/new.html.erb
<h2>New goal</h2>
<form class="" action="<%= goals_url %>" method="post">
  <%= auth_token %>
  <label for="title">Title</label>
  <input type="text" name="goal[title]" value="" id="title">

  <br>
  <label for="body">Body</label>
  <input type="text" name="goal[body]" value="" id="body">
  <br>
  <input type="submit" value="submit">
</form>

W5D1/GoalSetter/app/views/goals/show.html.erb
<h4><%= @goal.title %></h4>
<p>
  <%= @goal.body %>
</p>
<a href="<%= edit_goal_url(@goal) %>" id="edit">Edit goal</a>
<br>
<form action="<%= goal_url(@goal) %>" method="post">
  <%= auth_token %>
  <input type="hidden" name="_method" value="DELETE">

  <input type="submit" name="name" value="delete">
</form>

W5D1/GoalSetter/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GoalSetter</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if logged_in? %>
  Hi, <%= current_user.username %>!
  <form action="<%= session_url %>" method="post">
    <%= auth_token %>
    <input type="hidden" name="_method" value="DELETE">
    <input type="submit" value="Log out">
  </form>
<% else %>
  <a href="<%= new_session_url %>">Log in</a>
<% end %>
<%= yield %>

</body>
</html>

W5D1/GoalSetter/app/views/users/new.html.erb
<h2>Sign up</h2>

<form action="<%= users_url %>" method="post">
  <%= auth_token %>
  <label for="username">Username</label>
  <input type="text" name="user[username]" id="username">
  <label for="password">Password</label>
  <input type="password" name="user[password]" id="password">
  <input type="submit" value="submit">
</form>